import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import axios from "axios";
import { useEffect } from "react";

interface Video {
  name: string;
  url: string;
}

const Home: NextPage<{ videos: Video[] }> = ({ videos }) => {
  console.log(videos);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>test</main>
    </div>
  );
};

Home.getInitialProps = async (context) => {
  const { data } = await axios.get("http://localhost:3000/api/videos");
  return { videos: data };
};

export default Home;
